FROM alpine

RUN apk add influxdb

EXPOSE 8086
VOLUME [ "/var/lib/influxdb" ]
RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.13.3-static_linux_amd64.tar.gz
RUN tar -xvf telegraf-1.13.3-static_linux_amd64.tar.gz 
COPY ./telegraf.conf /etc/telegraf/telegraf.conf
COPY start.sh ./start.sh
RUN apk add supervisor
COPY supervisord.conf /etc/supervisord.conf
CMD  ./telegraf/telegraf & sh start.sh