FROM alpine:latest

RUN		wget https://dl.grafana.com/oss/release/grafana-7.2.1.linux-amd64.tar.gz
RUN tar -xvf grafana-7.2.1.linux-amd64.tar.gz
RUN rm -rf grafana-7.2.1.linux-amd64.tar.gz
RUN     apk add --no-cache libc6-compat
RUN mv grafana-7.2.1 grafana

RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.13.3-static_linux_amd64.tar.gz
RUN tar -xvf telegraf-1.13.3-static_linux_amd64.tar.gz 
COPY ./telegraf.conf /etc/telegraf/telegraf.conf
COPY dashboard/sample.yaml ./grafana/conf/provisioning/dashboards/sample.yaml
COPY dashboard/sampledb.yaml ./grafana/conf/provisioning/datasources/sample.yaml
COPY defaults.ini grafana/conf/defaults.ini
COPY dashboard/grafana.db grafana/data/grafana.db
EXPOSE 3000
CMD cd grafana/bin/; ./grafana-server  & ../../telegraf/telegraf