FROM alpine

RUN apk update
RUN apk add nginx
RUN apk add openrc
RUN apk add lighttpd php7-common php7-iconv php7-json php7-gd php7-curl php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom
RUN apk add php-fpm;
RUN apk add php-mysqli
RUN apk add php-session php7-mbstring


RUN mkdir -p /usr/share/webapps/
RUN wget http://files.directadmin.com/services/all/phpMyAdmin/phpMyAdmin-5.0.2-all-languages.tar.gz
RUN tar zxvf phpMyAdmin-5.0.2-all-languages.tar.gz
RUN rm phpMyAdmin-5.0.2-all-languages.tar.gz
RUN mv phpMyAdmin-5.0.2-all-languages phpmyadmin
RUN mv phpmyadmin /usr/share/webapps/
COPY config.inc.php /usr/share/webapps/phpmyadmin
RUN chmod -R 755 /usr/share/webapps/
RUN ln -s /usr/share/webapps/phpmyadmin/ /var/www/localhost/htdocs/phpmyadmin
RUN adduser -D -g 'www' www
RUN mkdir /www
RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /usr/share/webapps/
RUN mkdir -p /run/nginx

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY start.sh ./start.sh
RUN chmod +x /start.sh
RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.13.3-static_linux_amd64.tar.gz
RUN tar -xvf telegraf-1.13.3-static_linux_amd64.tar.gz
RUN mkdir /usr/share/webapps/phpmyadmin/tmp/
RUN chmod -R 777 /usr/share/webapps/phpmyadmin/tmp/
COPY ./telegraf.conf /etc/telegraf/telegraf.conf
RUN apk add supervisor
COPY supervisord.conf /etc/supervisord.conf
CMD sh ./start.sh

EXPOSE 5000
