FROM alpine:latest
RUN apk upgrade
RUN apk add vsftpd openssl openrc openssh

RUN openrc
RUN touch /run/openrc/softlevel
COPY start.sh start.sh

RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.13.3-static_linux_amd64.tar.gz
RUN tar -xvf telegraf-1.13.3-static_linux_amd64.tar.gz 
COPY ./telegraf.conf /etc/telegraf/telegraf.conf
RUN apk add supervisor
COPY supervisord.conf /etc/supervisord.conf
COPY vsftpd.userlist /etc/vsftpd.userlist


RUN adduser -D admin
RUN echo "admin:password" | chpasswd
RUN ssh-keygen -A
RUN yes "" | openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/certs/localhost.key -out /etc/ssl/certs/localhost.crt
COPY vsftpd.conf /etc/vsftpd/vsftpd.conf
RUN touch /home/admin/test.txt

CMD sh start.sh
EXPOSE 21 10000